### ISSUE TITLE
Issues generating PDF

### ISSUE THREAD

**Issue by alexroan** [ChainAccelOrg/audit-report-templating#1]
System: Macos

After following the instructions in the readme, running this command:

```
pandoc initial-report.md -o initial-report.pdf --from markdown --template=eisvogel --listings
```

produces this output:

```
pdflatex not found. Please select a different --pdf-engine or install pdflatex
```

Installing [TexLive](https://www.tug.org/texlive/) seemed to make some progress (`brew install texlive` - it's a biggy). Now when running the `pandoc` command I get this error:

```
Error producing PDF.
! LaTeX Error: Invalid UTF-8 byte sequence (�\lst@FillFixed@\lst@EC�).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.834 [⠆]
```

**Comment by PatrickAlphaC** [comment]
Looks like you have an issue with your markdown file. Do you have a sample minimal file that reproduces the issue?

**Comment by PatrickAlphaC** [comment]
Ah, this is because `⠆` is not a recognized character by pandoc. You'll need to remove it. I'll add this to the FAQ
