### ISSUE TITLE
Steps to Install Pandoc on Linux

### ISSUE THREAD

**Issue by the-first-elder** [ChainAccelOrg/audit-report-templating#2]
On Your terminal

```javascript

      sudo wget https://github.com/jgm/pandoc/releases/download/3.1.9/pandoc-3.1.9-1-amd64.deb
      sudo dpkg -i pandoc-3.1.9-amd64.deb

```

You can check the Pandoc official repository for the latest version.
https://github.com/jgm/pandoc/releases/

**Comment by PatrickAlphaC** [comment]
Thanks! I sort of want to leave the pandoc docs -> to the pandoc docs, I'm not sure I want to have people install pandoc based on what I have.
