### ISSUE TITLE
Installing Pandoc on windows using WSL Ubuntu

### ISSUE THREAD

**Issue by samtdomi** [ChainAccelOrg/audit-report-templating#3]
I have properly installed Pandoc - evidenced by being able to run `pandoc --help`  and getting the correct output.

However, I cannot `cd .pandoc` 

the error `no directory` keeps appearing. Therfore, I am unable to get into the templates folder and add `eisvogel.latex`.  I've been trying different ways of fixing this, but I cannot so far. I will continue but thought I'd reach out for some insight if anyone can help. 

Thank You!

**Comment by hosseinmirzapur** [comment]
> I have properly installed Pandoc - evidenced by being able to run `pandoc --help` and getting the correct output.
> 
> However, I cannot `cd .pandoc`
> 
> the error `no directory` keeps appearing. Therfore, I am unable to get into the templates folder and add `eisvogel.latex`. I've been trying different ways of fixing this, but I cannot so far. I will continue but thought I'd reach out for some insight if anyone can help.
> 
> Thank You!

Hello friend!

As I tried to install pandoc on my ubuntu I faced the same problem, so I searched a bit and I found out that you can create the `.pandoc` directory inside the home directory yourself and also don't forget to include `templates` directory inside the `.pandoc`. Seems a bit nasty but it's the way :)

**Comment by JDengin** [comment]
> > I have properly installed Pandoc - evidenced by being able to run `pandoc --help` and getting the correct output.
> > However, I cannot `cd .pandoc`
> > the error `no directory` keeps appearing. Therfore, I am unable to get into the templates folder and add `eisvogel.latex`. I've been trying different ways of fixing this, but I cannot so far. I will continue but thought I'd reach out for some insight if anyone can help.
> > Thank You!
> 
> Hello friend!
> 
> As I tried to install pandoc on my ubuntu I faced the same problem, so I searched a bit and I found out that you can create the `.pandoc` directory inside the home directory yourself and also don't forget to include `templates` directory inside the `.pandoc`. Seems a bit nasty but it's the way :)

I've encouter the same issue, I've use your method. Thank you

**Comment by JDengin** [comment]
> > I have properly installed Pandoc - evidenced by being able to run `pandoc --help` and getting the correct output.
> > However, I cannot `cd .pandoc`
> > the error `no directory` keeps appearing. Therfore, I am unable to get into the templates folder and add `eisvogel.latex`. I've been trying different ways of fixing this, but I cannot so far. I will continue but thought I'd reach out for some insight if anyone can help.
> > Thank You!
> 
> Hello friend!
> 
> As I tried to install pandoc on my ubuntu I faced the same problem, so I searched a bit and I found out that you can create the `.pandoc` directory inside the home directory yourself and also don't forget to include `templates` directory inside the `.pandoc`. Seems a bit nasty but it's the way :)

Just create pandoc and templates directory doesn't fix the issue, you can do that easily with command line and even copy the file `eisvogel.latex` inside. You can use that trick but after when you'll run the command `pandoc report-example.md -o report.pdf --from markdown --template=eisvogel --listings` for pdf creating you'll get the issue **_Could not find data file /usr/share/pandoc/data/templates/eisvogel.latex_**

Probably, what you have to do is copy the files `eisvogel.latex` inside the directory which the path is `\\wsl.localhost\Ubuntu\usr\share\pandoc\data\templates` in your computer, unfortunately when trying to do that manually or even with command line the access is denied. 

Access is denied I think because you cannot copy a file from Windows to WSL, even when I try to create a new file inside the given directory it's not allowed. I think it's an issue only Windows's users who have installed WSL face, probably Linux's users don't face that issue.

Always looking for a way to fix that issue, I think the key is to find a way to move a file from Windows to WSL.

**Comment by JDengin** [comment]
> > > I have properly installed Pandoc - evidenced by being able to run `pandoc --help` and getting the correct output.
> > > However, I cannot `cd .pandoc`
> > > the error `no directory` keeps appearing. Therfore, I am unable to get into the templates folder and add `eisvogel.latex`. I've been trying different ways of fixing this, but I cannot so far. I will continue but thought I'd reach out for some insight if anyone can help.
> > > Thank You!
> > 
> > 
> > Hello friend!
> > As I tried to install pandoc on my ubuntu I faced the same problem, so I searched a bit and I found out that you can create the `.pandoc` directory inside the home directory yourself and also don't forget to include `templates` directory inside the `.pandoc`. Seems a bit nasty but it's the way :)
> 
> Just create pandoc and templates directory doesn't fix the issue, you can do that easily with command line and even copy the file `eisvogel.latex` inside. You can use that trick but after when you'll run the command `pandoc report-example.md -o report.pdf --from markdown --template=eisvogel --listings` for pdf creating you'll get the issue **_Could not find data file /usr/share/pandoc/data/templates/eisvogel.latex_**
> 
> Probably, what you have to do is copy the files `eisvogel.latex` inside the directory which the path is `\\wsl.localhost\Ubuntu\usr\share\pandoc\data\templates` in your computer, unfortunately when trying to do that manually or even with command line the access is denied.
> 
> Access is denied I think because you cannot copy a file from Windows to WSL, even when I try to create a new file inside the given directory it's not allowed. I think it's an issue only Windows's users who have installed WSL face, probably Linux's users don't face that issue.
> 
> Always looking for a way to fix that issue, I think the key is to find a way to move a file from Windows to WSL.

I found a way to copy with command line the file `eisvogel.latex` inside appropriate folder, that is the command I used: 

`folder_where_eisvogel.latex_is_located_in_your_computer $ sudo cp eisvogel.latex /usr/share/pandoc/data/templates` 
for me by example it give me the command :

`jd_unix@JD-DELL-PC:/mnt/c/Users/JD/Downloads$  sudo cp eisvogel.latex /usr/share/pandoc/data/templates`

**Comment by S23Web3** [comment]
indeed,
after installing pandoc,
solution is to go to your home folder and 
`mkdir .pandoc/templates` 

There is were the eisvogel.latex template should be pasted in. 

I looked into several separate installs and all did not create this folder.
After installing and pasting in the template it worked for me (i also installed LaTex).

Searching online it seems it is not auto created.

**Comment by PatrickAlphaC** [comment]
Added a new alt way to make pdfs, let me know if that addresses the issue
