### ISSUE TITLE
## PDF generation Error

### ISSUE THREAD

**Issue by zacx-maker** [ChainAccelOrg/audit-report-templating#4]
#1 Hello i'm having issues generating pdf, i'm getting these error
```
pandoc report.md -o report.pdf --from markdown --template=eisvogel --listings 
Error producing PDF.
! LaTeX Error: File `footnotebackref.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.109 \setlength
```
what can i do?

**Comment by JDengin** [comment]
> #1 Hello i'm having issues generating pdf, i'm getting these error
> 
> ```
> pandoc report.md -o report.pdf --from markdown --template=eisvogel --listings 
> Error producing PDF.
> ! LaTeX Error: File `footnotebackref.sty' not found.
> 
> Type X to quit or <RETURN> to proceed,
> or enter new name. (Default extension: sty)
> 
> Enter file name: 
> ! Emergency stop.
> <read *> 
>          
> l.109 \setlength
> ```
> 
> what can i do?

I had a similar issue, try to ask in ChatGPT  **how to fix LaTeX Error: File `footnotebackref.sty' not found ?**. It provides interesting solutions

**Comment by PatrickAlphaC** [comment]
Damn, looks like there is this weird additional requirement. 

https://github.com/Wandmalfarbe/pandoc-latex-template/issues/141

Have you seen this?

**Comment by PatrickAlphaC** [comment]
Closing due to stale
